"""Artifact metadata, upload sessions, and signed URL orchestration."""

from __future__ import annotations

import json
from datetime import UTC, datetime, timedelta
from typing import Any
from uuid import uuid4

from sqlalchemy import select

from src.core.platform_contracts import ArtifactKind, ArtifactState
from src.persistence.database import PlatformDatabase
from src.persistence.models import ArtifactRecord, ArtifactUploadSessionRecord, ProjectMembershipRecord
from src.storage.base import ArtifactStorage
from src.storage.local import LocalArtifactStorage


class ArtifactService:
    def __init__(self, database: PlatformDatabase, storage: ArtifactStorage, signed_url_ttl_seconds: int) -> None:
        self._database = database
        self._storage = storage
        self._signed_url_ttl_seconds = signed_url_ttl_seconds

    def begin_upload(
        self,
        *,
        project_id: str,
        actor_id: str,
        kind: ArtifactKind,
        original_filename: str,
        mime_type: str,
        expected_size_bytes: int,
        expected_sha256: str | None,
    ) -> dict[str, Any]:
        artifact_id, session_id = str(uuid4()), str(uuid4())
        key = f"projects/{project_id}/artifacts/{artifact_id}/payload"
        expires_at = datetime.now(UTC) + timedelta(seconds=self._signed_url_ttl_seconds)
        with self._database.session() as session:
            session.add(
                ArtifactRecord(
                    id=artifact_id,
                    project_id=project_id,
                    created_by_user_id=actor_id,
                    kind=kind.value,
                    state=ArtifactState.UPLOADING.value,
                    storage_key=key,
                    original_filename=original_filename,
                    mime_type=mime_type,
                )
            )
            session.add(
                ArtifactUploadSessionRecord(
                    id=session_id,
                    artifact_id=artifact_id,
                    project_id=project_id,
                    expected_sha256=expected_sha256,
                    expected_size_bytes=expected_size_bytes,
                    expires_at=expires_at,
                )
            )
        upload_url = (
            f"/api/v1/projects/{project_id}/artifact-upload-sessions/{session_id}/content"
            if isinstance(self._storage, LocalArtifactStorage)
            else self._storage.signed_upload_url(
                key, mime_type=mime_type, expires_seconds=self._signed_url_ttl_seconds, sha256=expected_sha256
            )
        )
        return {
            "artifact_id": artifact_id,
            "upload_session_id": session_id,
            "upload_url": upload_url,
            "expires_at": expires_at,
        }

    def create_internal(
        self,
        *,
        project_id: str,
        actor_id: str,
        kind: ArtifactKind,
        original_filename: str,
        mime_type: str,
        content: bytes,
        state: ArtifactState = ArtifactState.QUARANTINED,
        metadata: dict[str, Any] | None = None,
        run_id: str | None = None,
    ) -> dict[str, Any]:
        """Persist bytes generated by a trusted worker without an upload session."""
        _validate_storage_segment(project_id, "project_id")
        if run_id is not None:
            _validate_storage_segment(run_id, "run_id")
        artifact_id = str(uuid4())
        key = (
            f"projects/{project_id}/runs/{run_id}/artifacts/{artifact_id}/payload"
            if run_id is not None
            else f"projects/{project_id}/artifacts/{artifact_id}/payload"
        )
        stored = self._storage.put_bytes(key, content, mime_type=mime_type)
        now = datetime.now(UTC)
        stored_metadata = dict(metadata or {})
        if run_id is not None:
            stored_metadata["run_id"] = run_id
        with self._database.session() as session:
            record = ArtifactRecord(
                id=artifact_id,
                project_id=project_id,
                created_by_user_id=actor_id,
                kind=kind.value,
                state=state.value,
                storage_key=key,
                sha256=stored.sha256,
                size_bytes=stored.size_bytes,
                mime_type=stored.mime_type or mime_type,
                original_filename=original_filename,
                metadata_json=json.dumps(stored_metadata, sort_keys=True),
                finalized_at=now,
            )
            session.add(record)
            session.flush()
            return _artifact_payload(record)

    def _check_actor_permission(self, record: ArtifactRecord, actor_id: str | None, session: Any = None) -> None:
        if actor_id is None:
            return
        if record.created_by_user_id == actor_id or actor_id.lower() in {"admin", "system", "system_auto", "internal"}:
            return
        if session is not None:
            membership = session.scalar(
                select(ProjectMembershipRecord).where(
                    ProjectMembershipRecord.project_id == record.project_id,
                    ProjectMembershipRecord.user_id == actor_id,
                    ProjectMembershipRecord.status == "ACTIVE",
                )
            )
            if membership is not None:
                return
        raise PermissionError("INSUFFICIENT_PERMISSION: Actor not authorized for this project artifact.")

    def upload_local_content(
        self, project_id: str, session_id: str, content: bytes, actor_id: str | None = None
    ) -> None:
        if not isinstance(self._storage, LocalArtifactStorage):
            raise ValueError("DIRECT_UPLOAD_NOT_AVAILABLE")
        with self._database.session() as session:
            upload_session, artifact = self._load_session(session, project_id, session_id)
            self._assert_open_session(upload_session)
            self._check_actor_permission(artifact, actor_id, session)
            if len(content) != upload_session.expected_size_bytes:
                raise ValueError("ARTIFACT_SIZE_MISMATCH")
            self._storage.put_bytes(
                artifact.storage_key,
                content,
                mime_type=artifact.mime_type or "application/octet-stream",
                sha256=upload_session.expected_sha256,
            )

    def complete_upload(
        self,
        project_id: str,
        session_id: str,
        claimed_sha256: str,
        claimed_size_bytes: int,
        actor_id: str | None = None,
    ) -> dict[str, Any]:
        with self._database.session() as session:
            upload_session, artifact = self._load_session(session, project_id, session_id)
            self._assert_open_session(upload_session)
            self._check_actor_permission(artifact, actor_id, session)
            object_info = self._storage.head(artifact.storage_key)
            if (
                object_info.size_bytes != claimed_size_bytes
                or object_info.size_bytes != upload_session.expected_size_bytes
            ):
                raise ValueError("ARTIFACT_SIZE_MISMATCH")
            if upload_session.expected_sha256 and upload_session.expected_sha256 != claimed_sha256:
                raise ValueError("ARTIFACT_HASH_MISMATCH")
            artifact.state = ArtifactState.QUARANTINED.value
            artifact.sha256 = object_info.sha256 or claimed_sha256
            artifact.size_bytes = object_info.size_bytes
            artifact.mime_type = object_info.mime_type or artifact.mime_type
            artifact.finalized_at = datetime.now(UTC)
            upload_session.completed_at = datetime.now(UTC)
            return _artifact_payload(artifact)

    def get(self, project_id: str, artifact_id: str, actor_id: str | None = None) -> dict[str, Any] | None:
        with self._database.session() as session:
            record = session.scalar(
                select(ArtifactRecord).where(ArtifactRecord.project_id == project_id, ArtifactRecord.id == artifact_id)
            )
            if record is None:
                return None
            self._check_actor_permission(record, actor_id, session)
            return _artifact_payload(record)

    def signed_download_url(self, project_id: str, artifact_id: str, actor_id: str | None = None) -> str | None:
        with self._database.session() as session:
            artifact = session.scalar(
                select(ArtifactRecord).where(ArtifactRecord.project_id == project_id, ArtifactRecord.id == artifact_id)
            )
            if artifact is None:
                return None
            self._check_actor_permission(artifact, actor_id, session)
            if artifact.state != ArtifactState.READY.value:
                return None
            return self._storage.signed_download_url(artifact.storage_key, self._signed_url_ttl_seconds)

    def read_bytes(self, project_id: str, artifact_id: str, actor_id: str | None = None) -> bytes:
        with self._database.session() as session:
            artifact = session.scalar(
                select(ArtifactRecord).where(ArtifactRecord.project_id == project_id, ArtifactRecord.id == artifact_id)
            )
            if artifact is None:
                raise KeyError("ARTIFACT_UNKNOWN")
            self._check_actor_permission(artifact, actor_id, session)
            return self._storage.get_bytes(artifact.storage_key)

    def list_for_run(self, project_id: str, run_id: str, actor_id: str | None = None) -> list[dict[str, Any]]:
        """Return only non-deleted artifacts explicitly attached to one project/run."""
        with self._database.session() as session:
            records = session.scalars(
                select(ArtifactRecord).where(
                    ArtifactRecord.project_id == project_id,
                    ArtifactRecord.deleted_at.is_(None),
                )
            ).all()
            result: list[dict[str, Any]] = []
            for record in records:
                self._check_actor_permission(record, actor_id, session)
                payload = _artifact_payload(record)
                if payload["metadata"].get("run_id") == run_id:
                    result.append(payload)
            return result

    def set_state(self, artifact_id: str, state: ArtifactState, *, metadata: dict[str, Any] | None = None) -> None:
        with self._database.session() as session:
            artifact = session.get(ArtifactRecord, artifact_id)
            if artifact is None:
                raise KeyError("ARTIFACT_UNKNOWN")
            artifact.state = state.value
            if metadata is not None:
                artifact.metadata_json = json.dumps(metadata, sort_keys=True)

    @staticmethod
    def _assert_open_session(upload_session: ArtifactUploadSessionRecord) -> None:
        now = datetime.now(UTC)
        expires_at = upload_session.expires_at
        if expires_at.tzinfo is None:
            expires_at = expires_at.replace(tzinfo=UTC)
        if upload_session.completed_at is not None:
            raise ValueError("UPLOAD_SESSION_COMPLETED")
        if expires_at <= now:
            raise ValueError("UPLOAD_SESSION_EXPIRED")

    @staticmethod
    def _load_session(
        session: Any, project_id: str, session_id: str
    ) -> tuple[ArtifactUploadSessionRecord, ArtifactRecord]:
        upload_session = session.scalar(
            select(ArtifactUploadSessionRecord).where(
                ArtifactUploadSessionRecord.id == session_id,
                ArtifactUploadSessionRecord.project_id == project_id,
            )
        )
        if upload_session is None:
            raise KeyError("UPLOAD_SESSION_UNKNOWN")
        artifact = session.get(ArtifactRecord, upload_session.artifact_id)
        if artifact is None:
            raise KeyError("ARTIFACT_UNKNOWN")
        return upload_session, artifact


def _artifact_payload(record: ArtifactRecord) -> dict[str, Any]:
    return {
        "id": record.id,
        "project_id": record.project_id,
        "created_by_user_id": record.created_by_user_id,
        "kind": record.kind,
        "state": record.state,
        "storage_key": record.storage_key,
        "sha256": record.sha256,
        "size_bytes": record.size_bytes,
        "mime_type": record.mime_type,
        "original_filename": record.original_filename,
        "metadata": json.loads(record.metadata_json),
        "created_at": record.created_at,
        "finalized_at": record.finalized_at,
        "deleted_at": record.deleted_at,
    }


def _validate_storage_segment(value: str, name: str) -> None:
    if not value or value in {".", ".."} or any(char in value for char in ("/", "\\", "\x00")):
        raise ValueError(f"INVALID_{name.upper()}")
