/**
 * Standard system configuration schemas, architecture definitions, and attack presets.
 */

export const PROBLEM_TYPES = [
  { id: "detection2d", name: "Object Detection", desc: "Phát hiện & định vị đối tượng 2D", icon: "Target" },
  { id: "segmentation", name: "SAM / Segmentation", desc: "Phân đoạn ảnh Semantic / Instance", icon: "Layers" },
  { id: "detection3d", name: "3D Detection", desc: "Phát hiện đối tượng trong không gian 3D", icon: "Box" },
  { id: "classification", name: "Classification", desc: "Phân loại hình ảnh đa lớp", icon: "Grid" },
  { id: "tracking", name: "Tracking", desc: "Theo dõi quỹ đạo đối tượng qua thời gian", icon: "Activity" },
];

export const MODEL_ARCHITECTURES = [
  { id: "yolo", name: "YOLO (v5 / v8 / v11)", family: "YOLO", defaultModel: "YOLO11s Clean (Local)", variants: ["yolo11s-clean-b0_best.pt", "surrogates/yolo11s.pt", "YOLOv8n", "YOLOv8s", "YOLO11n"] },
  { id: "pointpillars", name: "PointPillars 3D", family: "3D LiDAR", defaultModel: "pointpillars_kitti_3class.pth", variants: ["pointpillars_kitti_3class.pth (Local)"] },
  { id: "anonymization", name: "Anonymization ONNX", family: "Privacy ONNX", defaultModel: "yolo11n-face.onnx", variants: ["yolo11n-face.onnx (Local)", "yolov8n-license-plate.onnx (Local)"] },
  { id: "faster_rcnn", name: "Faster R-CNN", family: "2-Stage", defaultModel: "ResNet50-FPN", variants: ["ResNet50-FPN", "ResNet101-FPN"] },
  { id: "rtdetr", name: "RT-DETR", family: "Transformer", defaultModel: "RT-DETR-R50", variants: ["RT-DETR-R50", "RT-DETR-L"] },
  { id: "sam", name: "SAM 2.1", family: "Foundation", defaultModel: "SAM 2.1 (ViT-H)", variants: ["SAM 2.1 (ViT-H)", "SAM 2.1 (ViT-L)"] },
  { id: "mobilesam", name: "MobileSAM", family: "Edge SAM", defaultModel: "MobileSAM-L", variants: ["MobileSAM-L", "TinySAM"] },
  { id: "second", name: "SECOND", family: "3D LiDAR", defaultModel: "SECOND-Voxel", variants: ["SECOND-Voxel"] },
  { id: "bevfusion", name: "BEVFusion", family: "Multi-Modal", defaultModel: "BEVFusion-NuScenes", variants: ["BEVFusion-NuScenes"] },
];

export const CLASS_LABELS_DATA = [
  { id: 0, name: "person", count: 12543 },
  { id: 1, name: "car", count: 8732 },
  { id: 2, name: "bus", count: 1652 },
  { id: 3, name: "truck", count: 1235 },
  { id: 4, name: "motorbike", count: 3984 },
  { id: 5, name: "bicycle", count: 2120 },
  { id: 6, name: "traffic light", count: 1430 },
  { id: 7, name: "stop sign", count: 980 },
];

export const AVAILABLE_DATASETS = [
  {
    id: "kitti_anonymized_de",
    name: "KITTI De-anonymized Set (Local Workspace)",
    task: "detection2d",
    format: "PNG + Label TXT + Manifest",
    samples: 6,
    classes: 3,
    size: "14.2 MB",
    resolution: "1242 × 375",
    isLocal: true,
    localPath: "data/anonymized/kitti-de/",
    tags: ["local", "kitti", "autonomous-driving", "ready"],
    description: "Bộ dữ liệu KITTI có sẵn trong thư mục `data/anonymized/kitti-de/` (gồm các mẫu 000000.png, 000002.png... kèm nhãn bbox và manifest).",
    classLabels: [
      { id: 0, name: "Car", count: 18 },
      { id: 1, name: "Pedestrian", count: 6 },
      { id: 2, name: "Cyclist", count: 3 },
    ],
  },
  {
    id: "kitti_smoke_test",
    name: "KITTI Smoke Test Dataset (Local Workspace)",
    task: "detection2d",
    format: "PNG + Label TXT + Manifest",
    samples: 5,
    classes: 3,
    size: "11.8 MB",
    resolution: "1242 × 375",
    isLocal: true,
    localPath: "data/anonymized/kitti-smoke/",
    tags: ["local", "smoke-test", "pipeline"],
    description: "Bộ dữ liệu kiểm thử nhanh pipeline thị giác trong thư mục `data/anonymized/kitti-smoke/`.",
    classLabels: [
      { id: 0, name: "Car", count: 14 },
      { id: 1, name: "Pedestrian", count: 4 },
      { id: 2, name: "Cyclist", count: 2 },
    ],
  },
  {
    id: "kitti_3d_lidar",
    name: "KITTI 3D LiDAR Point Clouds (Thư mục data/kitti/)",
    task: "detection3d",
    format: "Velodyne Bin + Calib + Labels",
    samples: 7481,
    classes: 3,
    size: "12.8 GB",
    resolution: "Point Cloud 100k pts",
    isLocal: true,
    localPath: "data/kitti/Kitti/",
    tags: ["local", "3d", "lidar", "kitti"],
    description: "Bộ dữ liệu cảm biến LiDAR 64 tia và camera stereo nằm tại `data/kitti/` dùng cho phát hiện xe trong không gian 3D.",
    classLabels: [
      { id: 0, name: "Car", count: 28742 },
      { id: 1, name: "Pedestrian", count: 4487 },
      { id: 2, name: "Cyclist", count: 1627 },
    ],
  },
  {
    id: "coco_val2017",
    name: "MS COCO 2017 Validation Set",
    task: "detection2d",
    format: "COCO JSON",
    samples: 5000,
    classes: 80,
    size: "1.1 GB",
    resolution: "640 × 480",
    isLocal: false,
    tags: ["standard", "80-classes", "evaluation"],
    description: "Tập validation chuẩn 5,000 ảnh đa ngữ cảnh dùng để tính mAP@0.5:0.95 cho các mô hình thị giác.",
    classLabels: [
      { id: 0, name: "person", count: 11004 },
      { id: 1, name: "bicycle", count: 715 },
      { id: 2, name: "car", count: 1932 },
    ],
  },
  {
    id: "bdd100k_segmentation",
    name: "BDD100K Autonomous Driving Segmentation (Local)",
    task: "segmentation",
    format: "PNG Mask / JSON",
    samples: 10000,
    classes: 7,
    size: "4.2 GB",
    resolution: "1280 × 720",
    isLocal: true,
    localPath: "data/datasets/bdd100k/",
    tags: ["segmentation", "bdd100k", "weather", "ready"],
    description: "Tập dữ liệu phân đoạn giao thông BDD100K 10,000 ảnh đa thời tiết phục vụ đánh giá độ bền vững SAM 2.",
    classLabels: [
      { id: 0, name: "Car", count: 24100 },
      { id: 1, name: "Person", count: 8900 },
    ],
  },
];

export const AVAILABLE_MODELS = [
  {
    id: "local_sam2_hiera_small",
    name: "SAM 2.1 Hiera Small (image segmentation)",
    family: "SAM2.1",
    task: "segmentation",
    params: "46.0M",
    fileSize: "184.4 MB",
    inputSize: "1024 × 1024",
    format: ".pt (PyTorch)",
    isLocal: true,
    localPath: "checkpoints/sam2/sam2.1_hiera_small.pt",
    mapBaseline: "67.8% mIoU",
    fpsRtx4090: "85 FPS",
    description: "Mô hình phân đoạn ảnh; chỉ hiển thị READY khi checkpoint và dataset hợp lệ.",
    architecture: "sam",
  },
  {
    id: "local_yolo11s_clean",
    name: "YOLO11s (2D object detection)",
    family: "YOLO",
    task: "detection2d",
    params: "9.4M",
    fileSize: "19.1 MB",
    inputSize: "640 × 640",
    format: ".pt (PyTorch Weights)",
    isLocal: true,
    localPath: "data/checkpoints/yolo11s-clean-b0_best.pt",
    mapBaseline: "72.4%",
    fpsRtx4090: "120 FPS",
    description: "Checkpoint YOLO11s cho phát hiện đối tượng 2D; trạng thái chạy phụ thuộc checkpoint đã đăng ký.",
    architecture: "yolo",
  },
  {
    id: "pointpillars_kitti_local",
    name: "PointPillars (LiDAR 3D detection)",
    family: "3D LiDAR",
    task: "detection3d",
    params: "4.8M",
    fileSize: "19.2 MB",
    inputSize: "Point Cloud 100k pts",
    format: ".pth (MMDetection3D)",
    isLocal: true,
    localPath: "checkpoints/pointpillars/pointpillars_kitti_3class.pth",
    mapBaseline: "78.4% 3D mAP",
    fpsRtx4090: "62 FPS",
    description: "Car, Pedestrian, Cyclist; giữ WAITING_FOR_GPU_VALIDATION cho đến CUDA inference thật.",
    architecture: "pointpillars",
  },
  {
    id: "local_yolo11n_face",
    name: "yolo11n-face.onnx (Có sẵn trong checkpoints/anonymization)",
    family: "Privacy ONNX",
    task: "detection2d",
    params: "2.6M",
    fileSize: "5.2 MB",
    inputSize: "640 × 640",
    format: ".onnx (ONNX Runtime)",
    isLocal: true,
    localPath: "checkpoints/anonymization/yolo11n-face.onnx",
    mapBaseline: "91.4%",
    fpsRtx4090: "210 FPS",
    description: "Mô hình ONNX nhận diện và làm mờ khuôn mặt tự động để bảo vệ quyền riêng tư dữ liệu trước khi đánh giá.",
    architecture: "anonymization",
  },
];

export const ATTACK_PRESETS = [
  {
    id: "preset_weather_heavy",
    name: "🌧️ Thời tiết khắc nghiệt (Heavy Rain & Fog)",
    desc: "Mô phỏng sương mù dày đặc và mưa rơi theo chiều sâu làm mờ ống kính camera.",
    task: "detection2d",
    attacks: [
      { id: "depth_fog", name: "Depth Fog", severity: 3, eps: "Severity 3", alpha: "Depth", iters: 1 },
      { id: "depth_rain", name: "Depth Rain", severity: 4, eps: "Severity 4", alpha: "Depth", iters: 1 },
    ],
  },
  {
    id: "preset_gradient_stress",
    name: "⚡ Nhiễu Cảm Biến & Gradient (Sensor Stress Test)",
    desc: "Tổ hợp nhiễu hạt Gaussian ISO cao kết hợp đòn đối kháng gradient PGD.",
    task: "detection2d",
    attacks: [
      { id: "gaussian_noise", name: "Gaussian Noise", severity: 2, eps: "Severity 2", alpha: "L2", iters: 1 },
      { id: "pgd", name: "PGD (Projected Gradient)", severity: 3, eps: "8/255", alpha: "2/255", iters: 20 },
    ],
  },
  {
    id: "preset_3d_lidar",
    name: "📡 LiDAR Point Cloud Stress (3D Beam & Jitter)",
    desc: "Mô phỏng mất tia cảm biến LiDAR do bụi/mưa và nhiễu tọa độ 3D.",
    task: "detection3d",
    attacks: [
      { id: "lidar_beam_drop", name: "Beam Drop", severity: 3, eps: "Drop 30%", alpha: "Radial", iters: 1 },
      { id: "lidar_xyz_noise", name: "LiDAR XYZ Noise", severity: 3, eps: "σ=0.05m", alpha: "Gaussian", iters: 1 },
    ],
  },
];

export const ATTACK_CATEGORIES = [
  {
    category: "Thời tiết & Môi trường (Weather & Corruptions)",
    task_compatibility: ["detection2d", "segmentation", "classification"],
    attacks: [
      {
        id: "depth_fog",
        name: "Depth Fog",
        fullName: "Sương mù 3D có cảm nhận độ sâu",
        norm: "Natural",
        defaultEps: "Severity 3",
        isWeather: true,
        task_compatibility: ["detection2d", "segmentation"],
        desc: "Tạo sương mù tán xạ quang học dựa trên bản đồ độ sâu (Monocular Depth), làm suy giảm độ tương phản của vật thể ở xa trước.",
        previewClean: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=600&auto=format&fit=crop&q=80",
        previewAttacked: "https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?w=600&auto=format&fit=crop&q=80",
      },
      {
        id: "depth_rain",
        name: "Depth Rain",
        fullName: "Mưa rơi theo chiều sâu & vệt nước",
        norm: "Natural",
        defaultEps: "Severity 3",
        isWeather: true,
        task_compatibility: ["detection2d", "segmentation"],
        desc: "Sinh các vệt mưa rơi ngẫu nhiên theo vector vận tốc và vệt nước nhòe trên thấu kính camera.",
        previewClean: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=600&auto=format&fit=crop&q=80",
        previewAttacked: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=600&auto=format&fit=crop&q=80",
      },
      {
        id: "gaussian_noise",
        name: "Gaussian Noise",
        fullName: "Nhiễu hạt cảm biến ISO / Ánh sáng yếu",
        norm: "L2",
        defaultEps: "Severity 2",
        isWeather: true,
        task_compatibility: ["detection2d", "segmentation", "classification"],
        desc: "Thêm nhiễu phân phối chuẩn Gaussian vào từng pixel mô phỏng nhiễu cảm biến CMOS trong điều kiện thiếu sáng.",
        previewClean: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=600&auto=format&fit=crop&q=80",
        previewAttacked: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&auto=format&fit=crop&q=80",
      },
      {
        id: "motion_blur",
        name: "Motion Blur",
        fullName: "Mờ do rung lắc & xe di chuyển nhanh",
        norm: "Spatial",
        defaultEps: "Severity 3",
        isWeather: true,
        task_compatibility: ["detection2d", "segmentation"],
        desc: "Làm nhòe vệt chuyển động dọc theo vector vận tốc khi xe tự hành di chuyển ở tốc độ cao hoặc đường gập ghềnh.",
        previewClean: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=600&auto=format&fit=crop&q=80",
        previewAttacked: "https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=600&auto=format&fit=crop&q=80",
      },
    ],
  },
  {
    category: "Gradient-based (White-box)",
    task_compatibility: ["detection2d", "segmentation", "classification"],
    attacks: [
      {
        id: "pgd",
        name: "PGD",
        fullName: "Projected Gradient Descent",
        norm: "Linf",
        defaultEps: "8/255",
        task_compatibility: ["detection2d", "segmentation", "classification"],
        desc: "Tấn công gradient lặp từng bước có phép chiếu giới hạn L_inf, là chuẩn vàng mạnh nhất để kiểm thử lỗ hổng mô hình.",
        previewClean: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=600&auto=format&fit=crop&q=80",
        previewAttacked: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&auto=format&fit=crop&q=80",
      },
      {
        id: "fgsm",
        name: "FGSM",
        fullName: "Fast Gradient Sign Method",
        norm: "Linf",
        defaultEps: "8/255",
        task_compatibility: ["detection2d", "segmentation", "classification"],
        desc: "Tạo nhiễu đối kháng nhanh một bước (single-step) theo chiều đạo hàm hàm mất mát.",
        previewClean: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=600&auto=format&fit=crop&q=80",
        previewAttacked: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&auto=format&fit=crop&q=80",
      },
    ],
  },
  {
    category: "LiDAR & 3D Point Cloud",
    task_compatibility: ["detection3d"],
    attacks: [
      {
        id: "lidar_beam_drop",
        name: "Beam Drop",
        fullName: "Mất chùm tia cảm biến LiDAR",
        norm: "Spatial 3D",
        defaultEps: "Drop 30%",
        task_compatibility: ["detection3d"],
        desc: "Xóa ngẫu nhiên các chùm tia quét theo góc quét vòng tròn mô phỏng cảm biến bị che khuất hoặc bụi dính.",
        previewClean: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=600&auto=format&fit=crop&q=80",
        previewAttacked: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
      },
      {
        id: "lidar_xyz_noise",
        name: "LiDAR XYZ Noise",
        fullName: "Nhiễu tọa độ XYZ đám mây điểm",
        norm: "Gaussian 3D",
        defaultEps: "σ=0.05m",
        task_compatibility: ["detection3d"],
        desc: "Gây lệch tọa độ (X, Y, Z) của từng point theo phân phối Gaussian, làm biến dạng bề mặt voxel/pillar.",
        previewClean: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=600&auto=format&fit=crop&q=80",
        previewAttacked: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
      },
    ],
  },
];
